import { MigrationInterface, QueryRunner } from 'typeorm';

export class AutoGenerated1721344025479 implements MigrationInterface {
  name = 'AutoGenerated1721344025479';

  public async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(
      `ALTER TABLE "case" DROP CONSTRAINT "FK_541abe1313a414447a5dfb44479"`,
    );
    await queryRunner.query(
      `ALTER TABLE "advice" DROP CONSTRAINT "FK_9a03bb77bdcd862a4ea10665047"`,
    );
    await queryRunner.query(
      `ALTER TABLE "tag" DROP CONSTRAINT "FK_7af95683f9d0d8d0a76349611ea"`,
    );
    await queryRunner.query(
      `ALTER TABLE "schedule" DROP CONSTRAINT "FK_9c94e97526c0fc1a4d4a45af773"`,
    );
    await queryRunner.query(
      `ALTER TABLE "variable" DROP CONSTRAINT "FK_4970331c5e2080a759ee1206bd8"`,
    );
    await queryRunner.query(`ALTER TABLE "case" DROP COLUMN "created_by"`);
    await queryRunner.query(`ALTER TABLE "advice" DROP COLUMN "created_by"`);
    await queryRunner.query(`ALTER TABLE "tag" DROP COLUMN "created_by"`);
    await queryRunner.query(`ALTER TABLE "schedule" DROP COLUMN "createdById"`);
    await queryRunner.query(`ALTER TABLE "variable" DROP COLUMN "created_by"`);
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`ALTER TABLE "variable" ADD "created_by" integer`);
    await queryRunner.query(`ALTER TABLE "schedule" ADD "createdById" integer`);
    await queryRunner.query(`ALTER TABLE "tag" ADD "created_by" integer`);
    await queryRunner.query(`ALTER TABLE "advice" ADD "created_by" integer`);
    await queryRunner.query(`ALTER TABLE "case" ADD "created_by" integer`);
    await queryRunner.query(
      `ALTER TABLE "variable" ADD CONSTRAINT "FK_4970331c5e2080a759ee1206bd8" FOREIGN KEY ("created_by") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`,
    );
    await queryRunner.query(
      `ALTER TABLE "schedule" ADD CONSTRAINT "FK_9c94e97526c0fc1a4d4a45af773" FOREIGN KEY ("createdById") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`,
    );
    await queryRunner.query(
      `ALTER TABLE "tag" ADD CONSTRAINT "FK_7af95683f9d0d8d0a76349611ea" FOREIGN KEY ("created_by") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`,
    );
    await queryRunner.query(
      `ALTER TABLE "advice" ADD CONSTRAINT "FK_9a03bb77bdcd862a4ea10665047" FOREIGN KEY ("created_by") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`,
    );
    await queryRunner.query(
      `ALTER TABLE "case" ADD CONSTRAINT "FK_541abe1313a414447a5dfb44479" FOREIGN KEY ("created_by") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`,
    );
  }
}
