import { MigrationInterface, QueryRunner } from "typeorm";

export class AutoGenerated1721642591414 implements MigrationInterface {
    name = 'AutoGenerated1721642591414'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "case_response" DROP COLUMN "recipient_email"`);
        await queryRunner.query(`ALTER TABLE "case_response" DROP COLUMN "sent_at"`);
        await queryRunner.query(`ALTER TABLE "case_response" ADD "select_advices" jsonb`);
        await queryRunner.query(`ALTER TABLE "case_response" ADD "select_at" TIMESTAMP NOT NULL DEFAULT now()`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "case_response" DROP COLUMN "select_at"`);
        await queryRunner.query(`ALTER TABLE "case_response" DROP COLUMN "select_advices"`);
        await queryRunner.query(`ALTER TABLE "case_response" ADD "sent_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "case_response" ADD "recipient_email" character varying(255) NOT NULL`);
    }

}
