import { MigrationInterface, QueryRunner } from "typeorm";

export class AutoGenerated1721520693167 implements MigrationInterface {
    name = 'AutoGenerated1721520693167'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "schedule_activity_log" DROP CONSTRAINT "FK_541e6c243eceff2211398017e02"`);
        await queryRunner.query(`CREATE TYPE "public"."schedules_status_enum" AS ENUM('Active', 'Inactive')`);
        await queryRunner.query(`CREATE TABLE "schedules" ("id" SERIAL NOT NULL, "name" character varying(255) NOT NULL, "description" text, "start_timestamp" TIMESTAMP NOT NULL, "end_timestamp" TIMESTAMP, "is_recurring" boolean NOT NULL DEFAULT false, "status" "public"."schedules_status_enum" NOT NULL DEFAULT 'Active', "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "case_id" integer, "user_id" integer NOT NULL, CONSTRAINT "PK_7e33fc2ea755a5765e3564e66dd" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "schedule_recurrences" ("id" SERIAL NOT NULL, "frequency" character varying(50) NOT NULL, "interval" integer DEFAULT '1', "days_of_week" text, "days_of_month" text, "months_of_year" text, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "schedule_id" integer, CONSTRAINT "PK_fd499022cf589e7b47f7fcced31" PRIMARY KEY ("id"))`);
        await queryRunner.query(`ALTER TABLE "schedules" ADD CONSTRAINT "FK_9acdfa1137bc5ae58dc69089648" FOREIGN KEY ("case_id") REFERENCES "case"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "schedules" ADD CONSTRAINT "FK_55e6651198104efea0b04568a88" FOREIGN KEY ("user_id") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "schedule_recurrences" ADD CONSTRAINT "FK_869ba2bbd7510f5885959f81102" FOREIGN KEY ("schedule_id") REFERENCES "schedules"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "schedule_activity_log" ADD CONSTRAINT "FK_541e6c243eceff2211398017e02" FOREIGN KEY ("scheduleId") REFERENCES "schedules"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "schedule_activity_log" DROP CONSTRAINT "FK_541e6c243eceff2211398017e02"`);
        await queryRunner.query(`ALTER TABLE "schedule_recurrences" DROP CONSTRAINT "FK_869ba2bbd7510f5885959f81102"`);
        await queryRunner.query(`ALTER TABLE "schedules" DROP CONSTRAINT "FK_55e6651198104efea0b04568a88"`);
        await queryRunner.query(`ALTER TABLE "schedules" DROP CONSTRAINT "FK_9acdfa1137bc5ae58dc69089648"`);
        await queryRunner.query(`DROP TABLE "schedule_recurrences"`);
        await queryRunner.query(`DROP TABLE "schedules"`);
        await queryRunner.query(`DROP TYPE "public"."schedules_status_enum"`);
        await queryRunner.query(`ALTER TABLE "schedule_activity_log" ADD CONSTRAINT "FK_541e6c243eceff2211398017e02" FOREIGN KEY ("scheduleId") REFERENCES "Schedules"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

}
