import { MigrationInterface, QueryRunner } from "typeorm";

export class AutoGenerated1721485961533 implements MigrationInterface {
    name = 'AutoGenerated1721485961533'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "schedule_activity_log" DROP CONSTRAINT "FK_541e6c243eceff2211398017e02"`);
        await queryRunner.query(`CREATE TYPE "public"."Schedules_status_enum" AS ENUM('Active', 'Inactive')`);
        await queryRunner.query(`CREATE TABLE "Schedules" ("id" SERIAL NOT NULL, "name" character varying(255) NOT NULL, "description" text, "start_timestamp" TIMESTAMP NOT NULL, "end_timestamp" TIMESTAMP, "is_recurring" boolean NOT NULL DEFAULT false, "status" "public"."Schedules_status_enum" NOT NULL DEFAULT 'Active', "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "case_id" integer, "user_id" integer NOT NULL, CONSTRAINT "PK_364f08c10e5a443bf4a2125e702" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "ScheduleRecurrences" ("id" SERIAL NOT NULL, "frequency" character varying(50) NOT NULL, "interval" integer DEFAULT '1', "days_of_week" character varying(50), "days_of_month" character varying(50), "months_of_year" character varying(50), "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "schedule_id" integer, CONSTRAINT "PK_bf4e11d02abc25da76a8103f794" PRIMARY KEY ("id"))`);
        await queryRunner.query(`ALTER TABLE "Schedules" ADD CONSTRAINT "FK_4e585a466094c0a7fc616940e5e" FOREIGN KEY ("case_id") REFERENCES "case"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "Schedules" ADD CONSTRAINT "FK_aa69346d42111434902fe4e6f6c" FOREIGN KEY ("user_id") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "ScheduleRecurrences" ADD CONSTRAINT "FK_5a373f54c6e04e5186e9df5f38e" FOREIGN KEY ("schedule_id") REFERENCES "Schedules"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "schedule_activity_log" ADD CONSTRAINT "FK_541e6c243eceff2211398017e02" FOREIGN KEY ("scheduleId") REFERENCES "Schedules"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "schedule_activity_log" DROP CONSTRAINT "FK_541e6c243eceff2211398017e02"`);
        await queryRunner.query(`ALTER TABLE "ScheduleRecurrences" DROP CONSTRAINT "FK_5a373f54c6e04e5186e9df5f38e"`);
        await queryRunner.query(`ALTER TABLE "Schedules" DROP CONSTRAINT "FK_aa69346d42111434902fe4e6f6c"`);
        await queryRunner.query(`ALTER TABLE "Schedules" DROP CONSTRAINT "FK_4e585a466094c0a7fc616940e5e"`);
        await queryRunner.query(`DROP TABLE "ScheduleRecurrences"`);
        await queryRunner.query(`DROP TABLE "Schedules"`);
        await queryRunner.query(`DROP TYPE "public"."Schedules_status_enum"`);
        await queryRunner.query(`ALTER TABLE "schedule_activity_log" ADD CONSTRAINT "FK_541e6c243eceff2211398017e02" FOREIGN KEY ("scheduleId") REFERENCES "schedule"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

}
