app_env: 'local'
port: 3000

database:
  type: 'postgres'
  host: 'localhost'
  port: '5432'
  username: 'postgres'
  password: 'postgres'
  db_name: 'postgres'

aws:
  region: 'us-west-2'
  accessKeyId: 'fakeAccessKeyId'
  secretAccessKey: 'fakeSecretAccessKey'
  platformApplicationArn: 'fakePlatformApplicationArn'

jwt:
  secret: 'secret'
  expireTime: '1d'

smtp:
  smtp_host: 'smtp.mailtrap.io'
  smtp_port: 587
  smtp_secure: 'false'
  smtp_user: 'fakeUser'
  smtp_pass: 'fakePass'
  smtp_from: 'fakeFrom'